
[Config]
	#Change to 'false' if you want to reactivate Nether Portals
	AntiNether = true
	#Change to 'false' if you want to reactivate End Portals
	AntiEnd = true
	#Change to 'true' if you want to disable Ender Eye to be thrown in the air
	AntiEye = true
	#Add here the dimensions that you want to block. Example: 'minecraft:the_nether' or 'minecraft:the_end'
	BlockedDimensions = ["twilightforest:twilight_forest", "jerotesvillage:second_round_world", "sgjourney:abydos", "sgjourney_in_ad_astra:cavum_tenebrae_orbit", "sgjourney:chulak", "sgjourney:lantea"]
	#Change to 'true' if you want to OPs to bypass the mod
	ShouldOPBypass = false
	#Change to 'true' if you want to disable the End Remastered Eye
	DisableEndRemasteredEye = false

