GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('vacuum_filter', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuum_filter')
        .tankScalingFunction(tier => tier * 3200)
    event.create('lime_slaker', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('lime_slaker')
        .tankScalingFunction(tier => tier * 3200)
    event.create('rod_and_ball_mill', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('rod_and_ball_mill')
        .tankScalingFunction(tier => tier * 3200)
    event.create('slurry_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('slurry_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('hydroheater', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('hydroheater')
        .tankScalingFunction(tier => tier * 3200)
    event.create('flash_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('flash_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('high_pressure_digester', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('high_pressure_digester')
        .tankScalingFunction(tier => tier * 3200)
    event.create('blow_off_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('blow_off_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('condensate_pot', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('condensate_pot')
        .tankScalingFunction(tier => tier * 3200)
    event.create('decanter', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('decanter')
        .tankScalingFunction(tier => tier * 3200)
    event.create('deep_cone_thickener', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('deep_cone_thickener')
        .tankScalingFunction(tier => tier * 3200)
    event.create('polishing_filter', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('polishing_filter')
        .tankScalingFunction(tier => tier * 3200)
    event.create('classifier', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('classifier')
        .tankScalingFunction(tier => tier * 3200)
    event.create('precipitation_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('precipitation_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('heat_exchanger', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('heat_exchanger')
        .tankScalingFunction(tier => tier * 3200)
      
})