//ignored: true
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('vacuum_filter', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuum_filter')
        .tankScalingFunction(tier => tier * 3200)
    event.create('fluid_cooler', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('fluid_cooler')
        .tankScalingFunction(tier => tier * 3200)
    event.create('fluid_bubbler', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('fluid_bubbler')
        .tankScalingFunction(tier => tier * 3200)
    event.create('lime_slaker', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('lime_slaker')
        .tankScalingFunction(tier => tier * 3200)
    event.create('rod_and_ball_mill', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('rod_and_ball_mill')
        .tankScalingFunction(tier => tier * 3200)
    event.create('slurry_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('slurry_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('hydroheater', 'simple', GTValues.LV, GTValues.MV, GTValues.HV) 
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('hydroheater')
        .tankScalingFunction(tier => tier * 3200)
    event.create('flash_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('flash_tank')
        .tankScalingFunction(tier => tier * 3200)
    event.create('high_pressure_digester', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('high_pressure_digester')
        .tankScalingFunction(tier => tier * 3200)
    event.create('blow_off_tank', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('blow_off_tank')
        .tankScalingFunction(tier => tier * 3200)
})